ansible_python_interpreter: /usr/bin/python3

k8s_manifests:
  # CNI
  - https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  # Cert Manager
  - "https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml"
  # Metrics
  # - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  # - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability.yaml
  # Expose Network
  # - https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml
