- name: Add VS Code repo (YUM)
  become: true
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == "RedHat"

- name: Setup VS Code Repo (DEB)
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Add Microsoft GPG key (APT)
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repo (APT)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        filename: vscode
        state: present

- name: Install VS Code
  become: true
  ansible.builtin.package:
    name: code
    state: present
