- name: Setup Visual Studio on Debian Family
  become: true
  when: ansible_os_family == "Debian"
  block:
    - name: Create keyring directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Microsoft GPG key (Debian)
      ansible.builtin.shell:
        cmd: "curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg"
        creates: /etc/apt/keyrings/microsoft.gpg

    - name: Add VS Code APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
        filename: vscode
        state: present

- name: Setup Visual Studio on RedHat Family
  become: true
  block:
    - name: Add VS Code YUM repository (RedHat/CoreOS)
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install VS Code on OSTree Variants
      when: ansible_distribution_release in ['Bazzite', 'Coreos', 'Kinoite', 'Silverblue']
      community.general.rpm_ostree_pkg:
        name: code
        state: present

- name: Install VS Code
  become: true
  when: ansible_distribution_release not in ['Bazzite', 'Coreos', 'Kinoite', 'Silverblue']
  ansible.builtin.package:
    name: code
    state: present