- name: Initialize playbook
  ansible.builtin.debug:
    msg: "Starting Home Lab Setup in {{ inventory_hostname }}"

- name: Get OS Information
  ansible.builtin.command:
    cmd: lsb_release -a
  register: os_info
  changed_when: false

- name: Print OS Information
  ansible.builtin.debug:
    var: os_info.stdout_lines

- name: Install Core Deps
  become: true
  ansible.builtin.package:
    name:
      - build-essential
    update_cache: true
