- name: Vault Install
  ansible.builtin.import_tasks: install.yml
  when: vault_install | bool | default(false)

- name: Server Config Setup
  ansible.builtin.import_tasks: setup.yml
  when: vault_setup | bool | default(false)

- name: Client Config Setup
  ansible.builtin.import_tasks: client.yml
  when: "'workstation' in group_names"
