- name: Vault Install
  ansible.builtin.import_tasks: install.yml
  when: vault_install | bool | default(false)

- name: Server Config Setup
  ansible.builtin.import_tasks: setup.yml
  when: vault_setup | bool | default(false) and vault_root_token is defined

- name: Client Config Setup
  ansible.builtin.import_tasks: client.yml
  when: vault_install | bool | default(false) and 'workstation' in group_names
