# Bluetooth
bluetooth_enabled: true

# Kubernetes
k8s_enabled: true

# Graphics
graphics: intel

# NFS
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

nfs_exports:
  - path: /mnt/multimedia2
    clients: "192.168.1.0/24"
    options: "rw,async,no_subtree_check,no_root_squash"

nfs_mounts: []
