# Bluetooth
bluetooth_enabled: true

# Kubernetes
k8s_enabled: true

# Graphics
graphics: intel

# NFS
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

nfs_exports:
  - path: /mnt/music

nfs_mounts: []
