# LACP Variables
# bond_enabled: true
bond_dhcp:
  # enabled: true
  address: 192.168.1.10
  gateway: 192.168.1.1
bond_interfaces: [enp1s0, enp3s0]

# Zerotier
zerotier_enabled: false

# Bluetooth
bluetooth_enabled: true

# Kubernetes
k8s_enabled: true
k8s_pod_cidr: 10.244.0.0/16

# Graphics
graphics: intel

# NFS
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

nfs_exports:
  - path: /mnt/multimedia2
    clients: "192.168.1.0/24"
    options: "rw,async,no_subtree_check,no_root_squash"

nfs_mounts: []
