# ------------------------------------------------------------------------------
# System & Hardware
# ------------------------------------------------------------------------------
bluetooth_enabled: true
nfs_enabled: true
nfs_client_enabled: true

# ------------------------------------------------------------------------------
# Secret Management
# ------------------------------------------------------------------------------
vault_enabled: true
vault_install: true

# ------------------------------------------------------------------------------
# Development Tools
# ------------------------------------------------------------------------------
dev_tools_enabled:
  chrome: true
  gh: true
  nvm: true
  uv: true
  vscode: true
