# ------------------------------------------------------------------------------
# System & Hardware
# ------------------------------------------------------------------------------
bluetooth_enabled: true
nfs_enabled: true
nfs_client_enabled: true

# ------------------------------------------------------------------------------
# Secret Management
# ------------------------------------------------------------------------------
vault_enabled: true

# ------------------------------------------------------------------------------
# Development Tools
# ------------------------------------------------------------------------------
gh_enabled: true
nodejs_enabled: true
