# ------------------------------------------------------------------------------
# System & Hardware
# ------------------------------------------------------------------------------
nfs_enabled: true
nfs_server_enabled: true
nfs_client_enabled: true

# ------------------------------------------------------------------------------
# Secret Management
# ------------------------------------------------------------------------------
vault_enabled: true
vault_install: true

# ------------------------------------------------------------------------------
# Development Tools
# ------------------------------------------------------------------------------
dev_tools_enabled: true

dev_tools:
  chrome: true
  direnv: true
  gh: false
  nvm: true
  terraform: true
  uv: true
  vscode: true

# ------------------------------------------------------------------------------
# User Apps
# ------------------------------------------------------------------------------
steam_enabled: false
supersonic_enabled: true
vmware_enabled: false
