name: Update Server via Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  playbook:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: "Install Ansible"
        run: |
          pip3 install --upgrade pip
          pip3 install ansible ansible-core

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/barista@catuai
          chmod 600 ~/.ssh/id_ed25519
          printf "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: ansible-playbook playbook.yml
